# This is a basic workflow to help you get started with Actions

name: Code Quality

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  package-standardization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install Dependencies
        run: flutter pub get
      - name: Install Dependencies on handle_request_example
        run: flutter pub get
        working-directory: doc/handle_request_example
      - name: Format
        run: flutter pub publish --dry-run
      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Flutter Analyze
        run: flutter analyze
  unit-test:
    needs: package-standardization
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: run unit test
        run: flutter test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
