# This is a basic workflow to help you get started with Actions

name: Code Quality

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  package-standardization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install Dependencies
        run: flutter pub get
      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed .
      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Flutter Analyze
        run: flutter analyze
  code_quality:
    needs: package-standardization
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: 2.10.5
          channel: "stable"
      - name: Install Dependencies
        run: flutter pub get
      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Flutter Analyze
        run: flutter analyze
